# Cranky Configuration Example

[root]
name = "bar"
height = 40
left = ["workspace"]
center = ["hour"]
right = ["metrics", "systray"]

[root.margin]
top = 8
bottom = -8
left = 8
right = 8

[render]
mode = "immediate"
fps_limit = 30

[metrics]
update_interval_ms = 1000
cpu_mode = "gauge"
memory_mode = "gauge"
disks_mode = "gauge"
network_mode = "text"
temperature_mode = "text"
temp_fahrenheit = false

[modules.workspace]
border_radius = 4.0
active = { background_color = "#565f89" }

[modules.hour]
format = "%H:%M:%S %d/%m/%Y"

[modules.metrics]
network = false
temperature = false

[modules.systray]
show_icons = true
show_titles = false
icon_size = 22

[modules.mpris]
show_icon = true


